appscore/Web/Models/ErrorViewModel.cs
using System;

namespace Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

appscore/Web/ViewModels/HomeViewModels/IndexViewModel.cs
 

using System.Collections.Generic;

namespace Web.ViewModels.HomeViewModels
{
    public class IndexViewModel
    {
        public IEnumerable<Job> Jobs { get; set; }
    }
}

appscore/Web/ViewModels/Job.cs
 
using System;

namespace Web.ViewModels
{
    public class Job
    {
        public int JobId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Company { get; set; }
        public DateTime PostedDate { get; set; }
        public string Location { get; set; }
    }
}

appscore/Web/ViewModels/JobApplicant.cs
namespace Web.ViewModels
{
    public class JobApplicant
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public int ApplicantId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
    }
}

appscore/Web/ViewModels/JobsViewModels/ApplySuccessViewModel.cs
namespace Web.ViewModels.JobsViewModels
{
    public class ApplySuccessViewModel
    {
        public Job Job { get; }
        public long RecentApplicantCount { get; }

        public ApplySuccessViewModel(Job job, long recentApplicantCount)
        {
            Job = job;
            RecentApplicantCount = recentApplicantCount;
        }
    }
}

appscore/Web/ViewModels/JobsViewModels/ApplyViewModel.cs
 

namespace Web.ViewModels.JobsViewModels
{
    public class ApplyViewModel
    {
        public Job Job { get; }
        public User Applicant { get; }

        public ApplyViewModel(Job job,User applicant)
        {
            Job = job;
            Applicant = applicant;
        }
    }
}

appscore/Web/ViewModels/JobsViewModels/JobApplicationViewModel.cs
 

namespace Web.ViewModels.JobsViewModels
{
    public class JobApplicationViewModel
    {
       public User Applicant { get; set; }
       public Job Job { get; set; }
    }
}

appscore/Web/ViewModels/User.cs
namespace Web.ViewModels
{
    public class User
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Avatar { get; set; }
    }
}

appscore/Web/Controllers/HomeController.cs
 
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.Models;
using Web.Services;
using Web.ViewModels.HomeViewModels;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IJobService _jobService;
 

        public HomeController(IJobService jobService)
        {
            _jobService = jobService;
         
        }

        public async Task<IActionResult> Index()
        {
            return View(new IndexViewModel { Jobs = await _jobService.GetJobs() });
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

appscore/Web/Controllers/JobsController.cs
using System;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.Services;
using Web.ViewModels;
using Web.ViewModels.JobsViewModels;

namespace Web.Controllers
{
    public class JobsController : Controller
    {
        private readonly IJobService _jobService;
        private readonly IIdentityService _identityService;

        public JobsController(IJobService jobService, IIdentityService identityService)
        {
            _jobService = jobService;
            _identityService = identityService;
        }

        // GET jobs/apply/5
        [HttpGet("jobs/apply/{id}")]
        public async Task<IActionResult>  Apply(int id)
        {
            var job = await _jobService.GetJob(id);
            var applicant = await _identityService.GetUserAsync("1"); // hardcoded to user we stashed in identity service
            return View(new ApplyViewModel(job,applicant));
        }

        // POST jobs/apply
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Apply(JobApplicationViewModel model)
        {
            await _jobService.AddApplicant(new JobApplicant
            {
                Email = model.Applicant.Email,
                Name = model.Applicant.Name,
                ApplicantId = Convert.ToInt32(model.Applicant.Id),
                JobId = model.Job.JobId
            });

            return RedirectToAction("ApplySuccess",new{jobId=model.Job.JobId,applicantId= model.Applicant.Id });
        }

        // GET jobs/apply/success/5
        [HttpGet("jobs/apply/success/{id}")]
        public async Task<IActionResult> ApplySuccess(int jobId,string applicantId)
        {
            await Task.Delay(500); // give a sec for redis to eventually update
            var job = await _jobService.GetJob(jobId);
            var applicationCount = await _identityService.GetUserApplicationCountAsync(applicantId);
            return View(new ApplySuccessViewModel(job,applicationCount));
        }
    }
}

appscore/Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

appscore/Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

appscore/Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    @model Web.ViewModels.HomeViewModels.IndexViewModel
}

<div class="row">
    <div class="col-md-8">
        <h1>New Jobs (@Model.Jobs.Count())</h1>
        <hr class="no-margin" />
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        @foreach (var job in Model.Jobs)
            {
            <div class="posting">
                <div class="title-container">
                    <h3>@job.Title</h3>
                    <span>@job.Company | @job.Location | posted on @job.PostedDate.ToString("MM/dd/yyyy")</span>
                </div>
                <p class="description">@job.Description</p>
                <a class="btn btn-success" href="@Url.Action("Apply", "Jobs", new {id = job.JobId})" role="button">Apply for this job</a>
                <hr />
            </div>
        }
    </div>
</div>

appscore/Web/Views/Jobs/Apply.cshtml
@{
    ViewData["Title"] = "Apply for a gig";
    @model Web.ViewModels.JobsViewModels.ApplyViewModel
}

<div class="row">
    <div class="col-md-6 posting-apply">
        <h2>@Model.Job.Title</h2>
        <p class="post-meta">@Model.Job.Company | @Model.Job.Location | posted on @Model.Job.PostedDate.ToString("MM/dd/yyyy")</p>
        <p>@Model.Job.Description</p>
        <hr />
        <form asp-action="Apply" method="post">
            <p>You're applying as:</p>
            <input type="hidden" asp-for="Applicant.Id" />
            <input type="hidden" asp-for="Job.JobId" />
            <div class="form-group">
                <label>Email address</label>
                <input type="email" class="form-control" asp-for="Applicant.Email" placeholder="Your email" readonly>
            </div>
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" asp-for="Applicant.Name" placeholder="Your name" readonly>
            </div>
            <button type="submit" class="btn btn-success">Apply for this job</button>
        </form>

    </div>
</div>

appscore/Web/Views/Jobs/ApplySuccess.cshtml
@{
    ViewData["Title"] = "You've successfully applied to: " + Model.Job.Title;
    @model Web.ViewModels.JobsViewModels.ApplySuccessViewModel
}

<div class="row">
    <div class="col-md-8 application-success text-center">
        <h1>Way to go!</h1>
        <hr/>
        <p class="summary-description">You've successfully applied to <strong>@Model.Job.Company</strong> for the position of <strong>@Model.Job.Title</strong>.</p>
        <p class="summary-recent-count">You've recently applied for <strong class="recent-application-count">@Model.RecentApplicantCount</strong> job(s).</p>
        <a href="@Url.Action("Index", "Home")">Cool, let's go home.</a>
    </div>
</div>

appscore/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DotNetGigs - @ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DotNetGigs</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Today.Year - DotNetGigs</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>